
server:
  port: 9000
  tomcat:
    max-http-header-size: 8192
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/phototest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jtkj.mode



